# Generated by Django 5.1.7 on 2025-03-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armsApp', '0006_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='luggage_type',
            field=models.CharField(choices=[('hand_carry', 'Hand Carry (7kg max)'), ('checked_bag', 'Checked Baggage (23kg max)'), ('extra_bag', 'Extra Baggage (32kg max)'), ('sports_equipment', 'Sports Equipment'), ('musical_instrument', 'Musical Instrument'), ('special_item', 'Special Item')], default='hand_carry', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='luggage_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Weight (kg)'),
        ),
    ]
